[project]
name = 'healthcare-privacy-chain'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.access-control]
path = 'contracts/access-control.clar'
clarity_version = 2
epoch = 2.5

[contracts.healthcare-data]
path = 'contracts/healthcare-data.clar'
clarity_version = 2
epoch = 2.5

[contracts.patient-consent]
path = 'contracts/patient-consent.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
